### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by valzargaming** [reactphp/child-process#83] opened 2021-01-26 12:07 UTC
https://github.com/reactphp/child-process/blob/1110f31f2638044eeca939ca578d2ae2ebb44115/src/Process.php#L194
This line will cause a fatal error in PHP 8 because of changes in how accessing arrays is handled. `if ( isset(...) )` or comparative should be done first before attempting to check attribute/property/class/value/etc.

**Comment by clue** [comment] 2021-01-26 18:02
@valzargaming Thanks for reporting, I've indeed working on this this weekend and will file my PR as soon as possible :+1: 

This only affects the new PHP-8 only `socket` type in fdspec, so I consider this to be a new feature request rather than a bug. Expect a PR in the next couple of days now that #82 has been merged earlier today :shipit:

**Comment by clue** [comment] 2021-01-31 13:58
@valzargaming It seems like I might have misunderstood the problem you're seeing. I've just filed PHP 8 support with #85 and can not see the problem you're seeing. Can you provide a short gist to reproduce this?

**Comment by valzargaming** [comment] 2021-01-31 16:25
@clue It seems that whatever was causing the issue was resolved at one point as this error no longer occurs during testing. I tried a basic test by attempting to use the React/Filesystem to load a file and return it as a stream, but it still returns a 500 internal server error. Right now I am not sure if this is dependency-related.
![image](https://user-images.githubusercontent.com/7202504/106390450-8dd9f000-63b6-11eb-9b03-a8dce632e606.png)
![image](https://user-images.githubusercontent.com/7202504/106390458-916d7700-63b6-11eb-8328-1be7203740f5.png)

```php
$filesystem = \React\Filesystem\Filesystem::create($discord->getLoop()); //Awaiting full PHP 8 support
$rtmp = new Server($discord->getLoop(), function (ServerRequestInterface $request) use ($filesystem) {
	$file = $filesystem->file(__DIR__ . '/media/SpaceEngineers.mp4');
	return $file->exists()
		->then(
			function () use ($file) {
				return $file->open('r', true)
					->then(function ($stream) {
						echo '[TEST]' . __FILE__ . ':' . __LINE__ . PHP_EOL;
						file_put_contents('stream.txt', $stream); //0 bytes
						file_put_contents('stream.mp4', $stream); // 0 bytes
						return new Response(200, ['Content-Type' => 'video/mp4'], $stream);
					});
			},
			function () {
				return new Response(404, ['Content-Type' => 'text/plain'], "This video doesn't exist on server.");
			});
});
$rsocket = new \React\Socket\Server(sprintf('%s:%s', '0.0.0.0', '55554'), $discord->getLoop());
$rtmp->listen($rsocket);
```

**Comment by clue** [comment] 2021-01-31 17:03
@valzargaming It doesn't looks like this would be related to this project, so I'm closing this for now. Please file an issue in reactphp/http or reactphp/filesystem if the problem persists and I'm happy to take a look at this :+1:

**Closed by clue** 2021-01-31 17:03 UTC
Labels: question
